#pragma once

// Foreground

#define ANSI_PARAM_BLACK   "30"
#define ANSI_PARAM_RED     "31"
#define ANSI_PARAM_GREEN   "32"
#define ANSI_PARAM_YELLOW  "33"
#define ANSI_PARAM_BLUE    "34"
#define ANSI_PARAM_MAGENTA "35"
#define ANSI_PARAM_CYAN    "36"
#define ANSI_PARAM_WHITE   "37"
#define ANSI_PARAM_BRIGHT_BLACK   "90"
#define ANSI_PARAM_BRIGHT_RED     "91"
#define ANSI_PARAM_BRIGHT_GREEN   "92"
#define ANSI_PARAM_BRIGHT_YELLOW  "93"
#define ANSI_PARAM_BRIGHT_BLUE    "94"
#define ANSI_PARAM_BRIGHT_MAGENTA "95"
#define ANSI_PARAM_BRIGHT_CYAN    "96"
#define ANSI_PARAM_BRIGHT_WHITE   "97"

// Background

#define ANSI_PARAM_BG_BLACK   "40"
#define ANSI_PARAM_BG_RED     "41"
#define ANSI_PARAM_BG_GREEN   "42"
#define ANSI_PARAM_BG_YELLOW  "43"
#define ANSI_PARAM_BG_BLUE    "44"
#define ANSI_PARAM_BG_MAGENTA "45"
#define ANSI_PARAM_BG_CYAN    "46"
#define ANSI_PARAM_BG_WHITE   "47"
#define ANSI_PARAM_BG_BRIGHT_BLACK   "100"
#define ANSI_PARAM_BG_BRIGHT_RED     "101"
#define ANSI_PARAM_BG_BRIGHT_GREEN   "102"
#define ANSI_PARAM_BG_BRIGHT_YELLOW  "103"
#define ANSI_PARAM_BG_BRIGHT_BLUE    "104"
#define ANSI_PARAM_BG_BRIGHT_MAGENTA "105"
#define ANSI_PARAM_BG_BRIGHT_CYAN    "106"
#define ANSI_PARAM_BG_BRIGHT_WHITE   "107"

// Misc

#define ANSI_PARAM_BOLD       "1"
#define ANSI_RESET            "\x1b[0m"

#define ANSI_STYLE(...) ANSI_STYLE_CHOOSE_COMMAND(__VA_ARGS__, ANSI_STYLE_3, ANSI_STYLE_2, ANSI_STYLE_1)(__VA_ARGS__)
#define ANSI_STYLE_CHOOSE_COMMAND(_3, _2, _1, CMD, ...) CMD
#define ANSI_PARAM(STYLE) ANSI_PARAM_##STYLE
#define ANSI_STYLE_1(STYLE) "\x1b[" ANSI_PARAM(STYLE) "m"
#define ANSI_STYLE_2(STYLE1, STYLE2) "\x1b[" ANSI_PARAM(STYLE1) ";" ANSI_PARAM(STYLE2) "m"
#define ANSI_STYLE_3(STYLE1, STYLE2, STYLE3) "\x1b[" ANSI_PARAM(STYLE1) ";" ANSI_PARAM(STYLE2) ";" ANSI_PARAM(STYLE3) "m"